### PR TITLE
Add SVHN

### PR DESCRIPTION
**Pull request by fqdhlyc**
Add SVHN dataset, as well as implementing carlini attack on SVHN dataset.

### CODE REVIEW

**Comment by mzweilin** [comment]
Hi @fqdhlyc , thanks a bunch for the code contribution! Before I merge your pull request into the master branch, could you please make these quick fixes?

1. Remove the temporary files with the suffix ~;
2. Add a command line for downloading your pre-trained SVHN model; 
3. Make sure the example usage in README.md is runnable if we replace "MNIST" with "SVHN".

Best,
- Weilin

**Comment by fqdhlyc** [comment]
Hi Weilin,

I will make these changes as soon as I get a chance, thanks!

-Yuancheng Lin

________________________________

**Comment by evansuva** [comment]
Is this ready to merge now?

**Comment by fqdhlyc** [comment]
For 1. Done

2. For downloading pre-trained model download, I was thinking to include in https://github.com/mzweilin/EvadeML-Zoo/releases/download/v0.1/downloads.tar.gz
so that it is for users to download all models at once.

3. Will work if replace MNIST with SVHN, and model to tohinz. It will produce similar result like CIFAR10 with carlini model.

**Comment by mzweilin** [comment]
> For 1. Done
> 
> 1. For downloading pre-trained model download, I was thinking to include in https://github.com/mzweilin/EvadeML-Zoo/releases/download/v0.1/downloads.tar.gz
>    so that it is for users to download all models at once.
> 2. Will work if replace MNIST with SVHN, and model to tohinz. It will produce similar result like CIFAR10 with carlini model.

Could you provide the trained model so that I can integrate it into our downloads tarball?

**Comment by fqdhlyc** [comment]
Please check your school email, thanks.

________________________________

**Pull request merged**
